### ISSUE TITLE
Na novém Calibre nefunguje

### ISSUE THREAD

**Issue by burespe1** [Marduke/CalimeplPacz#16]
zdá se že v Calibre přešli na py 3.8 a s tím také na jinou strukturu pluginů...
```
calibre, version 5.10.1
CHYBA: Neošetřená výjimka: <b>ModuleNotFoundError</b>:No module named 'Queue'

calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: cs
Successfully initialized third party plugins: Comments Cleaner (1, 3, 2) && Consolidate All Library Metadata (2, 0, 40) && Find Duplicates (1, 8, 4) && Generate Cover (2, 0, 2) && QuarantineAndScrub (3, 6, 115) && Reformat plugin (2, 2, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.baila.__init__", line 21, in <module>
ModuleNotFoundError: No module named 'Queue'

```

**Comment by burespe1** [comment]
tak řešení snadné from Queue import Queue, => from queue import Queue, v _init_.py

**Comment by burespe1** [comment]
tady vypadá, že se tím zabývali a je zveřejněn funkční plugin k databázi knih
http://www.mobileread.mobi/forums/showthread.php?t=155524&page=13
